export default words = {
  possessive: {
    male: [
      "Son",
      "Ton"
    ],
    female: [
      "Sa",
      "Ta"
    ]
  },
  subject: {
    male: [
      "Lounis",
      "Benjamin",
      "Pacôme",
      "Sylvain",
      "Espéce",
      "frére",
      "pére",
      "cousin",
      "chien",
      "chat",
      "dromadaire",
    ],
    female: [
      "Espéce",
      "soeur",
      "mére",
      "cousine",
      "grande-tante",
      "souris",
    ]
  },
  pronom: {
    male: "le",
    female: "la"
  },
  amplifier: [
    "turbo",
    "ultra",
    "méga",
    "giga",
    "octo",
    "supra"
  ],
  name: {
    male: [
      "connard",
      "pain au lait",
      "étron",
      "prof de twerk",
      "scout",
      "tambourin",
      "babouin",
      "négre de maison",
      "gigolo",
      "sac à foutre",
      "esclave",
      "moule à gaufre",
      "jambonneau",
      "troue du cul",
      "couillon",
      "bougnoul",
      "homme de cro magnon",
      "sauvageon",
      "cadavre",
      "yéti",
      "paysan",
      "influenceur",
      "puceau",
      "power ranger jaune",
      "vélodrome"
    ],
    female: [
      "connasse",
      "pétasse",
      "grognasse",
      "prof de twerk",
      "scoute",
      "babouine",
      "secrétaire",
      "pute",
      "esclave",
      "femme de ménage",
      "couillonne",
      "tartelette",
      "macronade",
      "sauvageonne",
      "allumeuse",
      "boite d'allumette",
      "serpillère",
      "paysanne",
      "influenceuse",
      "pucelle",
      "moulaga",
    ]
  },
  adjectif: [
    "éclopé",
    "centenaire",
    "trisomique",
    "chauve",
    "suicidaire",
    "enculé",
    "sodomite",
    "obèse",
    "détraqué",
    "ravagé",
    "pauvre",
    "arabe",
    "attardé",
    "passioné",
    "drogué",
    "dépressif",
    "dépravé",
    "cancéreux",
    "nazi",
    "gay",
    "terroriste",
    "polygame",
    "pyromane",
  ],
  complement: [
    "mal lavé",
    "fatigué",
    "sur l'autoroute",
    "qui boit du sprit",
    "du bendo",
    "sur le périf\'",
    "dabbant ses grands morts",
    "qui sirote un pénis",
    "mal baisé",
    "qui mange ses morts",
    "écartelé",
    "noir",
    "séché",
    "lgbt",
    "décédé",
    "opprimé",
    "déformé",
    "qui baise une chévre",
    "savoyarde",
    "intolérant au lactose",
    "pas cuit",
    "frigide",
    "déformé",
    "satanique",
    "sans domicile fixe",
    "possédé",
    "démoniaque",
    "élevé dans un chenil",
    "né dans un chaudron",
    "en deuxième divison",
    "qui écoute du Céline Dion",
    "qui s'enfille des boules de geisha",
    "sponsorisé par Raid Shadow Legends",
    "en esprit",
    "sur des raviolis",
    "en clinique d'avortement"
  ]
}
